// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVMazeInfoAPI.Data;

#nullable disable

namespace TVMazeInfoAPI.Migrations
{
    [DbContext(typeof(TVMazeContext))]
    partial class TVMazeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShowId");

                    b.ToTable("Casts");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShowId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ShowId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Externals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imdb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.Property<int?>("Thetvdb")
                        .HasColumnType("int");

                    b.Property<int?>("Tvrage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowId")
                        .IsUnique()
                        .HasFilter("[ShowId] IS NOT NULL");

                    b.ToTable("Externals");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Medium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowId")
                        .IsUnique()
                        .HasFilter("[ShowId] IS NOT NULL");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PreviousEpisodeId")
                        .HasColumnType("int");

                    b.Property<int?>("SelfId")
                        .HasColumnType("int");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousEpisodeId");

                    b.HasIndex("SelfId");

                    b.HasIndex("ShowId")
                        .IsUnique()
                        .HasFilter("[ShowId] IS NOT NULL");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasFilter("[CountryCode] IS NOT NULL");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("ImageId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.PreviousEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreviousEpisode");

                    b.HasAnnotation("Relational:JsonPropertyName", "previousepisode");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Average")
                        .HasColumnType("float");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowId")
                        .IsUnique()
                        .HasFilter("[ShowId] IS NOT NULL");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Self", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Self");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AverageRuntime")
                        .HasColumnType("int");

                    b.Property<string>("DvdCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genres")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "genres");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NetworkId")
                        .HasColumnType("int");

                    b.Property<string>("OfficialSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premiered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Updated")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WebChannelId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId")
                        .IsUnique()
                        .HasFilter("[NetworkId] IS NOT NULL");

                    b.HasIndex("WebChannelId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.WebChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("WebChannel");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Cast", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithMany("Cast")
                        .HasForeignKey("ShowId");

                    b.Navigation("Character");

                    b.Navigation("Person");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Character", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Crew", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithMany("Crew")
                        .HasForeignKey("ShowId");

                    b.Navigation("Person");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Episode", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithMany("Episodes")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Externals", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithOne("Externals")
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Externals", "ShowId");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Image", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithOne("Image")
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Image", "ShowId");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Links", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.PreviousEpisode", "PreviousEpisode")
                        .WithMany()
                        .HasForeignKey("PreviousEpisodeId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Self", "Self")
                        .WithMany()
                        .HasForeignKey("SelfId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithOne("_links")
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Links", "ShowId");

                    b.Navigation("PreviousEpisode");

                    b.Navigation("Self");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Network", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Country", "Country")
                        .WithOne()
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Network", "CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Person", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Country");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Rating", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Show", "Show")
                        .WithOne("Rating")
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Rating", "ShowId");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Show", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Network", "Network")
                        .WithOne()
                        .HasForeignKey("TVMazeInfoAPI.Domain.Entities.Show", "NetworkId");

                    b.HasOne("TVMazeInfoAPI.Domain.Entities.WebChannel", "WebChannel")
                        .WithMany()
                        .HasForeignKey("WebChannelId");

                    b.Navigation("Network");

                    b.Navigation("WebChannel");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.WebChannel", b =>
                {
                    b.HasOne("TVMazeInfoAPI.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TVMazeInfoAPI.Domain.Entities.Show", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Crew");

                    b.Navigation("Episodes");

                    b.Navigation("Externals");

                    b.Navigation("Image");

                    b.Navigation("Rating");

                    b.Navigation("_links");
                });
#pragma warning restore 612, 618
        }
    }
}
